#!/bin/bash
# Copyright (C) 2024 Adam K Dean <adamkdean@googlemail.com>
# Use of this source code is governed by the GPL-3.0
# license that can be found in the LICENSE file.

SCW_BINARY=/opt/homebrew/bin/scw
PROFILES_FILE="$HOME/.scw_profiles.json"

function load_profile_env() {
    local profile_name=$(<"$HOME/.scw_current_profile")
    if [ -z "$profile_name" ]; then
        echo "No profile specified for environment setup"
        return 1
    fi

    local profile=$(jq -r ".[\"$profile_name\"]" $PROFILES_FILE)
    if [ "$profile" == "null" ]; then
        echo "Profile $profile_name does not exist for environment setup"
        return 1
    fi

    export SCW_ACCESS_KEY=$(echo $profile | jq -r '.SCW_ACCESS_KEY')
    export SCW_SECRET_KEY=$(echo $profile | jq -r '.SCW_SECRET_KEY')
    export SCW_DEFAULT_ORGANIZATION_ID=$(echo $profile | jq -r '.SCW_DEFAULT_ORGANIZATION_ID')
    export SCW_DEFAULT_PROJECT_ID=$(echo $profile | jq -r '.SCW_DEFAULT_PROJECT_ID')
}

function load_profile() {
    local profile_name=$1
    if [ -z "$profile_name" ]; then
        echo "No profile specified"
        exit 1
    fi

    local profile=$(jq -r ".[\"$profile_name\"]" $PROFILES_FILE)
    if [ "$profile" == "null" ]; then
        echo "Profile $profile_name does not exist"
        exit 1
    fi

    echo $profile_name > "$HOME/.scw_current_profile"
    echo "Profile $profile_name loaded"
}

function list_profiles() {
    local current_profile=$(cat "$HOME/.scw_current_profile" 2>/dev/null)
    echo "Available profiles:"
    jq -r 'to_entries[] | .key' "$PROFILES_FILE" | while read profile_name; do
        if [[ "$profile_name" == "$current_profile" ]]; then
            printf -- "- %s \e[32m(active)\e[0m\n" "$profile_name"
        else
            echo "- $profile_name"
        fi
    done
}

function current_profile() {
    local profile_name=$(<"$HOME/.scw_current_profile")
    echo "Current Profile: $profile_name"
}

function pass_through() {
    load_profile_env
    $SCW_BINARY "$@"
}

function usage() {
    echo "USAGE:"
    echo "  scw profile <command>"
    echo ""
    echo "AVAILABLE COMMANDS:"
    echo "  switch        Switch to a specific profile"
    echo "  list          List all available profiles"
    echo "  current       Show the current active profile"
    echo "  *             Any other command will be passed through to the original scw binary"
    echo ""
    echo "Use \"scw [command] --help\" for more information about a command."
}

case "$1" in
    profile)
        case "$2" in
            switch)
                load_profile "$3"
                ;;
            list)
                list_profiles
                ;;
            current)
                current_profile
                ;;
            *)
                usage
                exit 1
                ;;
        esac
        ;;
    *)
        pass_through "$@"
        ;;
esac
